project:
  type: website
  render:
    - "**.qmd"
    - "**.md"
    - ".github/CONTRIBUTING.md"
    - ".github/index.md"
    - "!docs/templates/"

website:
  title: "nf-modules"
  site-url: https://ccbr.github.io/nf-modules
  repo-url: https://github.com/CCBR/nf-modules
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: textbox
  navbar:
    title: false
    left:
      - text: home
        file: docs/index.qmd
      - text: modules
        file: docs/modules.qmd
      - text: subworkflows
        file: docs/subworkflows.qmd
    right:
      - icon: list
        menu:
          - text: Contributing
            file: .github/CONTRIBUTING.md
          - text: Changelog
            file: CHANGELOG.md
          - text: License
            file: LICENSE.md
      - icon: github
        href: https://github.com/CCBR/nf-modules

  page-footer:
    background: black
    foreground: white
    left: |
      [![](/_extensions/fnl/fnl-logo-dark.png){height=70px}](https://frederick.cancer.gov/research/science-areas/bioinformatics-and-computational-science/advanced-biomedical-computational-science)
    center: |
      Created by the
      [CCR Collaborative Bioinformatics Resource](https://github.com/CCBR)

execute:
  freeze: auto
format: fnl-html
