[workspace]
authors = ["Kelly Sovacool <kelly.sovacool@nih.gov>"]
channels = ["conda-forge", "bioconda"]
name = "nf-modules"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
nextflow = ">=25,<26"
nf-test = ">=0.9.5,<0.10"
nf-core = ">=4.1.0,<5"
