name: bam2fastq
description: |
  The module converts a BAM file to FASTQ format.
  It uses samtools bam2fq if reads are single end,
  or picard SamToFastq if reads are paired.

keywords:
  - bam2fq
  - samtools
  - fastq
  - picard
tools:
  - samtools:
      description: Tools for dealing with SAM, BAM and CRAM files
      documentation: http://www.htslib.org/doc/1.1/samtools.html
      licence: ["MIT"]
  - picard:
      description: |
        A set of command line tools (in Java) for manipulating high-throughput sequencing (HTS)
        data and formats such as SAM/BAM/CRAM and VCF.
      homepage: https://broadinstitute.github.io/picard/
      documentation: https://gatk.broadinstitute.org/hc/en-us/articles/360036510672-FastqToSam-Picard-
      tool_dev_url: https://github.com/broadinstitute/picard
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: BAM file
      pattern: "*.{bam,cram,sam}"
  - bai:
      type: file
      description: BAI (bam index) file
      pattern: "*.{bai}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - reads:
      type: file
      description: |
        1 fastq file if single end, or 2 fastq files if paired-end.
      pattern: "*.fastq.gz"
  - unpaired:
      type: file
      description: |
        unpaired reads
      pattern: "*.fastq.gz"
authors:
  - "@kelly-sovacool"
maintainers:
  - "@kelly-sovacool"
