contact_links:
  - name: Discussions
    url: https://github.com/CCBR/nf-modules/discussions # TODO replace CCBR_NextflowTemplate in this link with TOOL_NAME
    about: Please ask and answer questions here.
