name: samtools_filteraligned
description: Filter out aligned reads from a BAM file.
keywords:
  - bam
  - filter
  - samtools
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing reference information.
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: Input BAM file
output:
  - meta:
      type: map
      description: |
        Groovy Map containing reference information.
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: Output BAM file with only reads that were not aligned
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@kelly-sovacool"
maintainers:
  - "@kelly-sovacool"
