---
execute:
  echo: false
engine: knitr
---

<!-- This file is generated automatically from a template (docs/templates/modules.qmd) by docs/create-listings.py -->

```{r deps}
#| message: false
library(dplyr)
library(glue)
library(here)
library(knitr)
library(tidyr)
library(yaml)
meta <- yaml::read_yaml(here(params$nf_yaml_file))
yaml_to_df <- function(y) {
  is_leaf_entry <- function(x) {
    is.list(x) &&
      !is.null(names(x)) &&
      any(names(x) %in% c('type', 'description', 'pattern'))
  }

  normalize_fields <- function(x) {
    if (is.list(x)) {
      return(x)
    }
    list(value = as.character(x))
  }

  make_row <- function(name, fields, group) {
    c(
      list(group = group, name = name),
      normalize_fields(fields)
    ) %>%
      tibble::as_tibble_row()
  }

  collect_rows <- function(node, group = NA_character_) {
    if (!is.list(node)) {
      return(list())
    }

    node_names <- names(node)
    is_unnamed_list <- is.null(node_names) || !any(nzchar(node_names))

    if (is_unnamed_list) {
      return(
        purrr::map(node, collect_rows, group = group) %>%
          unlist(recursive = FALSE)
      )
    }

    purrr::imap(node, function(child, nm) {
      if (is_leaf_entry(child)) {
        return(list(make_row(name = nm, fields = child, group = group)))
      }

      if (is.list(child)) {
        next_group <- if (is.na(group)) nm else group
        return(collect_rows(child, group = next_group))
      }

      list()
    }) %>%
      unlist(recursive = FALSE)
  }

  rows <- collect_rows(y)

  if (length(rows) == 0) {
    return(tibble::tibble())
  }

  dplyr::bind_rows(rows) %>%
    dplyr::relocate(dplyr::any_of(c('group', 'name')))
}
```

```sh
nf-core `r params$module_type` \
  --git-remote https://github.com/CCBR/nf-modules \
  install `r params$module_name`
```

[{{< fa brands github >}}  https://github.com/CCBR/nf-modules/.../`r params$module_path`](https://github.com/CCBR/nf-modules/tree/main/`r params$module_path`)


## {{< fa arrow-right-to-bracket >}} Input

```{r input}
#| message: false
meta$input %>% yaml_to_df() %>% kable()
```

## {{< fa arrow-right-from-bracket >}} Output

```{r output}
#| message: false
meta$output %>% yaml_to_df() %>% kable()
```

```{r tools-markdown}
#| output: asis
home_symbol  <- '{{< fa solid globe >}}'
book_symbol  <- '{{< fa solid book >}}'
code_symbol <- '{{< fa regular file-code >}}'

if ('tools' %in% names(meta)) {
    tools_df <- meta$tools %>% yaml_to_df()
    for (colname in c('tool_dev_url', 'homepage', 'documentation', 'licence')) {
        if (!(colname %in% colnames(tools_df))) {
            tools_df[colname] <- NA_character_
        }
    }
    markdown <- tools_df %>%
      mutate(name = glue("### { name }"),
             home = case_when(!is.na(homepage) ~ glue("[{ home_symbol } Home]({ homepage })"),
                              TRUE ~ ""),
             docs = case_when(!is.na(documentation) ~ glue("[{ book_symbol } Docs]({ documentation })"),
                              TRUE ~ ""),
             code = case_when(!is.na(tool_dev_url) ~ glue("[{ code_symbol } Code]({ tool_dev_url })"),
                              TRUE ~ ""),
             license = case_when(!is.na(licence) ~ glue("`{ licence }`"),
                                 TRUE ~ ""),
             links = paste(home, docs, code, license,
                           sep = " &ensp; "),
             markdown = glue("{ name }", "{ links }", "{ description }",
                             .sep = '\n\n')
      ) %>%
      pull(markdown)
    cat('## {{< fa screwdriver-wrench >}} Tools \n\n')
    cat(paste(markdown, collapse = "\n\n"))
}
```
