---
name: "custom_combinepeakcounts"
description: combine counts into consensus peaks
keywords:
  - chipseq
  - peaks
  - consensus
tools:
  - "R":
      description: "R is a free software environment for statistical computing and graphics"
      homepage: "https://www.r-project.org/"
      licence: "GPL-3"

input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - counts:
      type: file
      description: peak file from bedtools/bedmap
      pattern: "*.bed"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - bed:
      type: file
      description: |
        consensus peak file

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@kelly-sovacool"
maintainers:
  - "@kelly-sovacool"
