---
name: "custom_consensuspeaks"
description: Find consensus peaks from two or more peak files.
keywords:
  - peaks
  - chipseq
  - normalization
  - consensus
tools:
  - Python:
      description: |
        The Python Programming Language
      homepage: https://www.python.org/
      licence: ["Python License 2.0"]
  - bedtools:
      description: |
        A set of tools for genomic analysis tasks, specifically enabling genome arithmetic (merge, count, complement) on various file types.
      documentation: https://bedtools.readthedocs.io/
      licence: ["MIT"]
  - bedops:
      description: |
        fast, highly scalable and easily-parallelizable genome analysis toolkit
      documentation: https://bedops.readthedocs.io/
      tool_dev_url: https://github.com/bedops/bedops
      licence: ["GPLv2"]
      doi: 10.1093/bioinformatics/bts277
  - bedSort:
      description: |
        UCSC Genome Browser tool for sorting .bed files by chrom,chromStart.
      documentation: https://www.encodeproject.org/software/bedsort/

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - peaks:
      type: file
      description: Peak files
      pattern: "*.{broadPeak,narrowPeak,bed}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  - peaks:
      type: file
      description: A single consensus peak file
      pattern: "*.{broadPeak,narrowPeak,bed}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@kelly-sovacool"
maintainers:
  - "@kelly-sovacool"
